<?php
	require('includes/header.php');
?>
<body>
<div id="container">
	<div id="masthead">
	<?php
		require('includes/menu.php');
	?>
	</div>
	<div id="content">
		<div id="content_inner">
			<h1>FAQ</h1>
			<h3>HOW DO I APPLY?</h3>
		<p>Y<?php print(strtolower('OU CAN APPLY BY CONTACTING US THROUGH REGISTERING TO OUR WEBSITE AND MESSAGING THE ADMIN.'));?></p>
<h3>WHAT IS SILKROAD LOOKING FOR IN A CHAPTER APPLICANT?</h3>
<p>W<?php print(strtolower('E ARE LOOKING FOR PASSIONATE STUDENTS WHO BELIEVE THAT EDUCATION IS A CALL TO ACTION. OUR CHAPTER LEADERS HAVE A HISTORY OF ACHIEVEMENT AND WANT TO DIVE DEEPER INTO ISSUES IN DEVELOPING COUNTRIES. OUR LEADERS ARE MOTIVATED INDIVIDUALS WHO WORK HARD AND CAN LEAD A GROUP WITH BOTH HANDS-ON AND OFF GUIDANCE FROM THE HQ. '));?></p>
<h3>HOW MUCH TIME COMMITMENT WILL BEING A CHAPTER FOUNDER ENTAIL?</h3>
<p>F<?php print(strtolower('OUNDING AND SUSTAINING A CHAPTER IS HARD WORK! POTENTIAL LEADERS WILL DEVOTE MUCH OF THEIR OUTSIDE CLASS TIME TO STARTING THE CHAPTER, GARNERING SUPPORT, AND PLANNING FOR EVENTS THROUGHOUT THE SEMESTER. THAT SAID, IF YOU HAVE GOOD TIME MANAGEMENT SKILLS AND ARE WILLING TO WORK HARD TO START A CHAPTER, WE ARE HERE TO HELP YOU ALONG THE WAY!'));?></p>
<h3>BEFORE APPLYING, WHAT ARE SOME THINGS I SHOULD CONSIDER?</h3>
<p>I<?php print(strtolower('F YOU HAVE A CO-FOUNDER OR HAVE A FEW PEOPLE WHO ARE READY TO BE ON YOUR CHAPTER BOARD, THIS WILL BE IMMENSELY HELPFUL FOR STARTING YOUR CHAPTER. THIS WILL HELP ESTABLISH YOUR CHAPTER IN A PROMPT MANNER SINCE YOU WILL ALREADY HAVE A SUPPORT TEAM TO WORK WITH. WE ENCOURAGE ALL POTENTIAL FOUNDERS TO LOOK FOR BOARD MEMBER SUPPORT BEFORE APPLYING.'));?></p>
<h3>WHAT WILL THE COMMUNICATION BETWEEN ME AND THE HQ BE LIKE?</h3>
<p>W<?php print(strtolower('E ARE HERE TO GUIDE AND ASSIST YOUR CHAPTER! CHAPTER LEADERS ARE REQUIRED TO BE INFORMED OF ALL ANNOUNCEMENTS, CAMPAIGNS, AND GUIDELINES WHICH WILL BE COMMUNICATED VIA EMAIL OR BY VIDEO CONFERENCE. CHAPTER LEADERS SHOULD BE COMMUNICATIVE VIA EMAIL AND ALSO FOR OCCASIONAL VIDEO CONFERENCES. OUR COMMUNICATION IS TO ENSURE THAT THE CHAPTERS AND THE HQ ARE ALIGNED AT ALL TIMES!'));?></p>
			
		</div>
	</div>
</div>
</body>
</html>
